### ISSUE TITLE
Create script to merge Legistar and CivicPlus sites into a single Google Spreadsheet

### ISSUE THREAD

**Issue by zstumgoren** [biglocalnews/aw-scripts#1]
This work is required in order to support numerous site features such as search filters and "Coverage Areas". 

We'll need to pull Legistar sites from dynamo db and CivicPlus sites from the sites CSV in civic-scraper repo and use that data to update a Google Spreadsheet containing metadata annotations #39

**Comment by fgregg** [comment]
@zstumgoren, can you just produce a list of legistar sites and we can take it from there.

**Comment by zstumgoren** [comment]
This is obsolete. See this [issue comment](https://github.com/biglocalnews/civic-prefect-flow-dev/issues/4#issuecomment-1303981619). Closing.
